models/Task.py
import datetime

from flask_wtf import FlaskForm
from sqlalchemy import Column, Integer, ForeignKey, text
from sqlalchemy.orm import relationship, validates
from wtforms import StringField, SubmitField, HiddenField, validators
from wtforms.fields.html5 import DateField, TimeField
from wtforms.validators import DataRequired, Length, ValidationError
from wtforms.widgets import TextArea


from flask_app import db


def _convert_results_to_tasks(result):
    # aggregate regular sql requirement
    aggregate_sql = text("SELECT task_id, COUNT(*) FROM reminder WHERE has_expired = 0 GROUP BY task_id;")
    aggregate_result = db.engine.execute(aggregate_sql)

    reminder_counts = {}
    for row in aggregate_result:
        reminder_counts[row[0]] = row[1]

    tasks = []
    # get name for user from result
    for row in result:
        if row[4]:
            start_time = (datetime.datetime.min + row[4]).time()
            end_time = (datetime.datetime.min + row[5]).time()
        else:
            start_time = None
            end_time = None

        task = Task(id=row[0], name=row[1], notes=row[2], date=row[3],
                    start_time=start_time,
                    end_time=end_time,
                    project_id=row[6], is_completed=row[7])

        if task.id in reminder_counts:
            task.reminder_count = reminder_counts[task.id]
        else:
            task.reminder_count = 0
        tasks.append(task)

    return tasks


def get_tasks_regular_sql(project_id):
    # compound regular sql requirement
    sql = text(f'select * from task WHERE project_id = {project_id} AND is_completed = 0;')
    result = db.engine.execute(sql)

    tasks = _convert_results_to_tasks(result)

    return tasks


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    name = db.Column(db.String(100), unique=False, nullable=False)
    notes = db.Column(db.Text, nullable=False, default="")

    date = db.Column(db.Date, nullable=False)
    start_time = db.Column(db.Time, nullable=True)
    end_time = db.Column(db.Time, nullable=True)

    project_id = Column(Integer, ForeignKey('project.id'))
    project = relationship("Project", back_populates="tasks")
    reminders = relationship("Reminder", back_populates="task", cascade="all,delete")
    is_completed = db.Column(db.Boolean, default=False)


class TaskForm(FlaskForm):
    class Meta:
        model = Task

    name = StringField('name', validators=[DataRequired(), Length(min=2, max=100)])
    project_id = HiddenField('project_id', validators=[DataRequired()])
    notes = StringField('Notes', widget=TextArea())
    date = DateField('DatePicker', format='%Y-%m-%d', validators=[DataRequired()])
    start_time = TimeField('Start time', validators=(validators.Optional(),))
    end_time = TimeField('End time', validators=(validators.Optional(),))
    submit = SubmitField('Sign Up')

    # def validate_date(self, field):
    #     today = datetime.datetime.now().date()
    #     value = field.data
    #     if value < today:
    #         raise ValidationError('Date must be later than today')

controllers/reminders_controller.py
from flask import Blueprint, redirect, url_for, flash, render_template, request
from flask_login import login_required, current_user

from flask_app import db
from models import Task
from models.Reminder import ReminderForm, Reminder
from models.Task import TaskForm

reminders_controller = Blueprint('reminders_controller', __name__)


@reminders_controller.route('/reminders/new', methods=['POST'])
@login_required
def new_reminder_post():
    form = ReminderForm()

    if form.validate_on_submit():
        flash(f'Reminder created!', 'success')
        reminder = Reminder()
        form.populate_obj(reminder)

        db.session.add(reminder)
        db.session.commit()
        task = reminder.task
        return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=TaskForm(),
                               project=task.project, task=task, reminder_form=form)

    else:
        for error_field, error_message in form.errors.items():
            flash(str(error_message), 'error')
        task = Task.query.filter(Task.id == form.task_id.data).first()
        return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=TaskForm(),
                               project=task.project, task=task, reminder_form=form)


@reminders_controller.route('/reminders/delete', methods=['GET'])
@login_required
def delete_reminder():
    reminder_id = request.args.get('reminder_id')

    reminder = Reminder.query.filter(Reminder.id == reminder_id)
    task_id = reminder.first().task.id
    if reminder:
        reminder.delete()
    db.session.commit()
    flash(f'Reminder deleted!', 'success')

    return redirect(url_for('tasks_controller.edit_task', task_id=task_id))

controllers/tasks_controller.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import login_required, current_user
from sqlalchemy import and_, text

from flask_app import db
from models.Project import Project
from models.Reminder import ReminderForm
from models.Task import TaskForm, Task

tasks_controller = Blueprint('tasks_controller', __name__)


@tasks_controller.route('/tasks/new', methods=['GET'])
@login_required
def index():
    form = TaskForm()
    project_id = request.args.get('project_id')
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()

    if project:
        form.project_id.data = project_id
        return render_template('task/index.html', project=project, title="New Task", form=form)
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/new', methods=['POST'])
@login_required
def new_task_post():
    form = TaskForm()
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == form.project_id.data)).first()

    if project:
        if form.validate_on_submit():
            flash(f'Task {form.name.data} created!', 'success')
            task = Task()
            form.populate_obj(task)
            task.project = project
            project.project_id = project.id

            db.session.add(project)
            db.session.commit()
            return redirect(url_for('projects_controller.edit_project', project_id=project.id))

        else:
            for error_field, error_message in form.errors.items():
                flash(str(error_message), 'error')
            return render_template('task/index.html', project=project, title="New Task", form=form)
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/edit', methods=['GET'])
@login_required
def edit_task():
    task_id = request.args.get('task_id')
    # filter using sqlalchemy requirement
    task = Task.query.filter(Task.id == task_id).first()

    # update subquery regular sql for requirement
    update_query = text("UPDATE reminder SET has_expired=1 WHERE id IN (SELECT id FROM (SELECT * FROM reminder) as r WHERE date_time <= NOW());")
    db.engine.execute(update_query)
    db.session.commit()

    if task:
        form = TaskForm(obj=task)
        return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=form,
                               task=task, project=task.project, reminder_form=ReminderForm(task_id=task.id))
    else:
        flash(f'Task does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/edit', methods=['POST'])
@login_required
def edit_task_post():
    form = TaskForm()
    task_id = request.args.get('task_id')
    task = Task.query.filter(Project.id == task_id).first()

    if task:
        if form.validate_on_submit():
            form.populate_obj(task)
            db.session.add(task)
            db.session.commit()

            flash(f'Successfully updated task.', 'success')
            return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=form,
                                   project=task.project, task=task, reminder_form=ReminderForm(task_id=task.id))
        else:
            flash(f'Error updating task.', 'error')
            return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=form,
                                   project=task.project, task=task, reminder_form=ReminderForm(task_id=task.id))
    else:
        flash(f'Task does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/delete', methods=['GET'])
@login_required
def delete_task():
    task_id = request.args.get('task_id')

    task = Task.query.filter(Task.id == task_id)
    project_id = task.first().project.id
    if task:
        task.delete()
    db.session.commit()
    flash(f'Task deleted!', 'success')

    return redirect(url_for('projects_controller.edit_project', project_id=project_id))

templates/task/edit.html
{% extends "base.html" %}
{% set active_page = "projects" %}

{% block content %}


<div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('projects_controller.index') }}">Projects</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('projects_controller.edit_project', project_id=project.id) }}"
                                       aria-current="page">{{ project.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ task.name }}</li>
      </ol>
    </nav>
</div>

<div class="row">
    <div class="col">
        <div class="card">
        <div class="card-header">
            Edit {{ task.name }}
        </div>
        <div class="card-body">
            <div class="row">

                <div class="col">
                    <form method="POST" action="{{ url_for("tasks_controller.edit_task_post", task_id=task.id) }}">
                        {{ form.hidden_tag() }}

                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Task Name:</div>
                                    {{ form.name(class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Notes:</div>
                                    {{ form.notes(class="form-control") }}
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Date:</div>
                                    {{ form.date(class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="row">
                                    <div class="col">
                                        <p>Only input times if task is a meeting instead of an assignment.</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="input-group">
                                            <div class="input-group-text">Start Time:</div>
                                            {{ form.start_time(class="form-control") }}
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="input-group">
                                            <div class="input-group-text">End Time:</div>
                                            {{ form.end_time(class="form-control") }}
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary">Edit Task</button>
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
</div>

<hr>
<div class="row">
    <div class="col">

        <div class="row">
            <div class="col">
                        <div class="card">
        <div class="card-header">
            Add Reminder
        </div>
        <div class="card-body">
            <div class="row">

                <div class="col">
                    <form method="POST" action="{{ url_for("reminders_controller.new_reminder_post") }}">
                        {{ reminder_form.hidden_tag() }}

                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Time:</div>
                                    {{ reminder_form.date_time(class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary">New Reminder</button>
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="row">
    <div class="col">
        <div class="row">
            <div class="col">
                <h3>Current Reminders</h3>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Time</th>
                      <th scope="col">Delete</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for reminder in task.reminders %}
                    <tr>
                        <td></td>
                      <td>{{ reminder.date_time.strftime('%Y-%m-%d %I:%M %p') }}</td>
                        <td><a class="btn btn-danger"
                               href="{{ url_for('reminders_controller.delete_reminder', reminder_id=reminder.id) }}">Delete</a></td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/task/index.html
{% extends "base.html" %}
{% set active_page = "projects" %}

{% block content %}


<div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('projects_controller.index') }}">Projects</a></li>
        <li class="breadcrumb-item"><a href="{{ url_for('projects_controller.edit_project', project_id=project.id) }}"
                                       aria-current="page">{{ project.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">New Task</li>
      </ol>
    </nav>
</div>

<div class="row">
    <div class="col">
        <div class="card">
        <div class="card-header">
            Add Task
        </div>
        <div class="card-body">
            <div class="row">

                <div class="col">
                    <form method="POST" action="{{ url_for("tasks_controller.new_task_post") }}">
                        {{ form.hidden_tag() }}

                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Task Name:</div>
                                    {{ form.name(class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Notes:</div>
                                    {{ form.notes(class="form-control") }}
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Date:</div>
                                    {{ form.date(class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="row">
                                    <div class="col">
                                        <p>Only input times if task is a meeting instead of an assignment.</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6">
                                        <div class="input-group">
                                            <div class="input-group-text">Start Time:</div>
                                            {{ form.start_time(class="form-control") }}
                                        </div>
                                    </div>
                                    <div class="col-6">
                                        <div class="input-group">
                                            <div class="input-group-text">End Time:</div>
                                            {{ form.end_time(class="form-control") }}
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary">Add Task</button>
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}