auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash

from models.User import User, RegistrationForm, LoginForm
from flask_app import db

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    form = LoginForm()
    return render_template('login.html', form=form, title="Log in")


@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))  # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))


@auth.route('/signup')
def signup():
    form = RegistrationForm()
    return render_template('signup.html', title='Register', form=form)


@auth.route('/signup', methods=['POST'])
def signup_post():
    form = RegistrationForm()

    if form.validate_on_submit():
        # convert password to hashed
        form.password.data = generate_password_hash(form.password.data)
        flash(f'Account created for {form.name.data}!', 'success')
        user = User()
        form.populate_obj(user)

        db.session.add(user)
        db.session.commit()
        return redirect(url_for('auth.login'))
    else:
        if "email" in form.errors:
            flash('Email must be unique.')
        return render_template('signup.html', title='Register', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

controllers/projects_controller.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from sqlalchemy import and_, text

from models import Task, User
from models.Project import ProjectForm, Project
from flask_app import db
from models.Task import _convert_results_to_tasks

projects_controller = Blueprint('projects_controller', __name__)


@projects_controller.route('/projects/index', methods=['GET'])
@login_required
def index():
    form = ProjectForm()
    active_projects, inactive_projects = Project.get_active_and_inactive_projects(current_user)
    return render_template('project/index.html', name=current_user.name, title="Projects", form=form,
                           projects=active_projects, inactive_projects=inactive_projects)


@projects_controller.route('/projects/upcoming', methods=['GET'])
@login_required
def upcoming():
    # join regular sql requirement
    tasks_sql = text('SELECT task.id AS task_id, task.name AS task_name, task.notes AS task_notes, task.date AS task_date,'
                     ' task.start_time AS task_start_time, task.end_time AS task_end_time, task.project_id AS task_project_id,'
                     ' task.is_completed AS task_is_completed FROM task JOIN project ON project.id = task.project_id JOIN '
                     'user ON user.id = project.user_id')
    tasks_results = db.engine.execute(tasks_sql)
    tasks = _convert_results_to_tasks(tasks_results)

    return render_template('project/upcoming.html', title="Upcoming", tasks=tasks)


@projects_controller.route('/projects/new', methods=['POST'])
@login_required
def new_project_post():
    form = ProjectForm()
    active_projects, inactive_projects = Project.get_active_and_inactive_projects(current_user)

    if form.validate_on_submit():
        flash(f'Project {form.name.data} created!', 'success')
        project = Project()
        form.populate_obj(project)
        project.user = current_user
        project.user_id = current_user.id

        db.session.add(project)
        db.session.commit()
        return redirect(url_for('projects_controller.index'))
    else:
        if "email" in form.errors:
            flash('Email must be unique.')
        return render_template('project/index.html', name=current_user.name, title="Projects", form=form,
                               projects=active_projects, inactive_projects=inactive_projects)


@projects_controller.route('/projects/deactivate', methods=['GET'])
@login_required
def deactivate_project():
    project_id = request.args.get('project_id')

    # compound sql condition using sqlalchemy for requirement
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()
    project.is_active = 0
    db.session.commit()
    flash(f'Project {project.name} deactivated!', 'success')

    return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/activate', methods=['GET'])
@login_required
def activate_project():
    project_id = request.args.get('project_id')

    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()
    project.is_active = 1
    db.session.commit()
    flash(f'Project {project.name} activated!', 'success')

    return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/delete', methods=['GET'])
@login_required
def delete_project():
    project_id = request.args.get('project_id')

    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id))
    if project:
        project.delete()
    db.session.commit()
    flash(f'Project deleted!', 'success')

    return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/edit', methods=['GET'])
@login_required
def edit_project():
    project_id = request.args.get('project_id')
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()

    if project:
        form = ProjectForm(obj=project)
        return render_template('project/edit.html', name=current_user.name, title=f"{project.name} | Edit", form=form,
                               project_id=project_id, tasks=Task.get_tasks_regular_sql(project_id))
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/edit', methods=['POST'])
@login_required
def edit_project_post():
    form = ProjectForm()
    project_id = request.args.get('project_id')
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()

    if project:
        if form.validate_on_submit():
            form.populate_obj(project)
            db.session.add(project)
            db.session.commit()

            flash(f'Successfully updated project.', 'success')
            return render_template('project/edit.html', name=current_user.name, title=f"{project.name} | Edit",
                                   form=form, tasks=Task.get_tasks_regular_sql(project_id))
        else:
            flash(f'Error updating project.', 'error')
            return render_template('project/edit.html', name=current_user.name, title=f"{project.name} | Edit",
                                   form=form, tasks=Task.get_tasks_regular_sql(project_id))
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/base.css" />

</head>

<body>

<div class="container">
  <header class="d-flex justify-content-center py-3">
    <ul class="nav nav-pills">
      <li class="nav-item">
          {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.profile') }}" class="nav-link {{ 'active' if active_page == 'home' else '' }}">
                                Home
                            </a></li>
          {% else %}
          <a href="{{ url_for('main.index') }}" class="nav-link {{ 'active' if active_page == 'home' else '' }}">
                                Home
                            </a></li>
          {% endif %}
              <li class="nav-item">{% if current_user.is_authenticated %}
                            <a href="{{ url_for('projects_controller.upcoming') }}" class="nav-link {{ 'active' if active_page == 'upcoming' else '' }}">
                                Upcoming
                            </a>
                            {% endif %}</li>
      <li class="nav-item">{% if current_user.is_authenticated %}
                            <a href="{{ url_for('projects_controller.index') }}" class="nav-link {{ 'active' if active_page == 'projects' else '' }}">
                                Projects
                            </a>
                            {% endif %}</li>
      <li class="nav-item">{% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="nav-link {{ 'active' if active_page == 'login' else '' }}">
                                Login
                            </a>
                            </li>
        <li class="nav-item">
                            <a href="{{ url_for('auth.signup') }}" class="nav-link {{ 'active' if active_page == 'signup' else '' }}">
                                Sign Up
                            </a>
                            {% endif %}</li>
      <li class="nav-item">{% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="nav-link {{ 'active' if active_page == 'logout' else '' }}">
                                Logout
                            </a>
                            {% endif %}</li>
    </ul>
  </header>
</div>

            <div class="container">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-primary">
                                {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

               {% block content %}
               {% endblock %}
            </div>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% set active_page = "home" %}

{% block content %}
<h1 class="title">
  Flask Login Example
</h1>
<h2 class="subtitle">
  Easy authentication and authorization in Flask.
</h2>
{% endblock %}