models/Project.py
from flask_wtf import FlaskForm
from sqlalchemy import Column, Integer, ForeignKey, text
from sqlalchemy.orm import relationship
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length
from wtforms.widgets import TextArea


from flask_app import db
from models.Reminder import Reminder
from models.Task import Task


class Project(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    name = db.Column(db.String(100), unique=True, nullable=False)
    notes = db.Column(db.Text, nullable=False, default="")

    user_id = Column(Integer, ForeignKey('user.id'))
    user = relationship("User", back_populates="projects")
    tasks = relationship("Task", back_populates="project", cascade="all,delete")

    is_active = db.Column(db.Boolean, default=True)

    @staticmethod
    def get_active_and_inactive_projects(current_user):
        active_projects = []
        inactive_projects = []
        for project in current_user.projects:
            if project.is_active:
                project.task = None
                project.reminder = None
                # get next task
                project.task = Task.query.filter_by(project_id=project.id).order_by(Task.date.desc()).first()

                if project.task:
                    # get next reminder - join sqlalchemy for requirement
                    project.reminder = Reminder.query.join(
                        Task, Task.project_id == project.task.id).order_by(Task.date.desc()).first()

                active_projects.append(project)
            else:
                inactive_projects.append(project)

        return active_projects, inactive_projects


class ProjectForm(FlaskForm):
    class Meta:
        model = Project

    name = StringField('name', validators=[DataRequired(), Length(min=2, max=100)])
    notes = StringField('Notes', widget=TextArea())
    submit = SubmitField('Sign Up')

controllers/projects_controller.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from sqlalchemy import and_, text

from models import Task, User
from models.Project import ProjectForm, Project
from flask_app import db
from models.Task import _convert_results_to_tasks

projects_controller = Blueprint('projects_controller', __name__)


@projects_controller.route('/projects/index', methods=['GET'])
@login_required
def index():
    form = ProjectForm()
    active_projects, inactive_projects = Project.get_active_and_inactive_projects(current_user)
    return render_template('project/index.html', name=current_user.name, title="Projects", form=form,
                           projects=active_projects, inactive_projects=inactive_projects)


@projects_controller.route('/projects/upcoming', methods=['GET'])
@login_required
def upcoming():
    # join regular sql requirement
    tasks_sql = text('SELECT task.id AS task_id, task.name AS task_name, task.notes AS task_notes, task.date AS task_date,'
                     ' task.start_time AS task_start_time, task.end_time AS task_end_time, task.project_id AS task_project_id,'
                     ' task.is_completed AS task_is_completed FROM task JOIN project ON project.id = task.project_id JOIN '
                     'user ON user.id = project.user_id')
    tasks_results = db.engine.execute(tasks_sql)
    tasks = _convert_results_to_tasks(tasks_results)

    return render_template('project/upcoming.html', title="Upcoming", tasks=tasks)


@projects_controller.route('/projects/new', methods=['POST'])
@login_required
def new_project_post():
    form = ProjectForm()
    active_projects, inactive_projects = Project.get_active_and_inactive_projects(current_user)

    if form.validate_on_submit():
        flash(f'Project {form.name.data} created!', 'success')
        project = Project()
        form.populate_obj(project)
        project.user = current_user
        project.user_id = current_user.id

        db.session.add(project)
        db.session.commit()
        return redirect(url_for('projects_controller.index'))
    else:
        if "email" in form.errors:
            flash('Email must be unique.')
        return render_template('project/index.html', name=current_user.name, title="Projects", form=form,
                               projects=active_projects, inactive_projects=inactive_projects)


@projects_controller.route('/projects/deactivate', methods=['GET'])
@login_required
def deactivate_project():
    project_id = request.args.get('project_id')

    # compound sql condition using sqlalchemy for requirement
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()
    project.is_active = 0
    db.session.commit()
    flash(f'Project {project.name} deactivated!', 'success')

    return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/activate', methods=['GET'])
@login_required
def activate_project():
    project_id = request.args.get('project_id')

    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()
    project.is_active = 1
    db.session.commit()
    flash(f'Project {project.name} activated!', 'success')

    return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/delete', methods=['GET'])
@login_required
def delete_project():
    project_id = request.args.get('project_id')

    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id))
    if project:
        project.delete()
    db.session.commit()
    flash(f'Project deleted!', 'success')

    return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/edit', methods=['GET'])
@login_required
def edit_project():
    project_id = request.args.get('project_id')
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()

    if project:
        form = ProjectForm(obj=project)
        return render_template('project/edit.html', name=current_user.name, title=f"{project.name} | Edit", form=form,
                               project_id=project_id, tasks=Task.get_tasks_regular_sql(project_id))
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@projects_controller.route('/projects/edit', methods=['POST'])
@login_required
def edit_project_post():
    form = ProjectForm()
    project_id = request.args.get('project_id')
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()

    if project:
        if form.validate_on_submit():
            form.populate_obj(project)
            db.session.add(project)
            db.session.commit()

            flash(f'Successfully updated project.', 'success')
            return render_template('project/edit.html', name=current_user.name, title=f"{project.name} | Edit",
                                   form=form, tasks=Task.get_tasks_regular_sql(project_id))
        else:
            flash(f'Error updating project.', 'error')
            return render_template('project/edit.html', name=current_user.name, title=f"{project.name} | Edit",
                                   form=form, tasks=Task.get_tasks_regular_sql(project_id))
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))

controllers/tasks_controller.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import login_required, current_user
from sqlalchemy import and_, text

from flask_app import db
from models.Project import Project
from models.Reminder import ReminderForm
from models.Task import TaskForm, Task

tasks_controller = Blueprint('tasks_controller', __name__)


@tasks_controller.route('/tasks/new', methods=['GET'])
@login_required
def index():
    form = TaskForm()
    project_id = request.args.get('project_id')
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == project_id)).first()

    if project:
        form.project_id.data = project_id
        return render_template('task/index.html', project=project, title="New Task", form=form)
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/new', methods=['POST'])
@login_required
def new_task_post():
    form = TaskForm()
    project = Project.query.filter(and_(Project.user_id == current_user.id, Project.id == form.project_id.data)).first()

    if project:
        if form.validate_on_submit():
            flash(f'Task {form.name.data} created!', 'success')
            task = Task()
            form.populate_obj(task)
            task.project = project
            project.project_id = project.id

            db.session.add(project)
            db.session.commit()
            return redirect(url_for('projects_controller.edit_project', project_id=project.id))

        else:
            for error_field, error_message in form.errors.items():
                flash(str(error_message), 'error')
            return render_template('task/index.html', project=project, title="New Task", form=form)
    else:
        flash(f'Project does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/edit', methods=['GET'])
@login_required
def edit_task():
    task_id = request.args.get('task_id')
    # filter using sqlalchemy requirement
    task = Task.query.filter(Task.id == task_id).first()

    # update subquery regular sql for requirement
    update_query = text("UPDATE reminder SET has_expired=1 WHERE id IN (SELECT id FROM (SELECT * FROM reminder) as r WHERE date_time <= NOW());")
    db.engine.execute(update_query)
    db.session.commit()

    if task:
        form = TaskForm(obj=task)
        return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=form,
                               task=task, project=task.project, reminder_form=ReminderForm(task_id=task.id))
    else:
        flash(f'Task does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/edit', methods=['POST'])
@login_required
def edit_task_post():
    form = TaskForm()
    task_id = request.args.get('task_id')
    task = Task.query.filter(Project.id == task_id).first()

    if task:
        if form.validate_on_submit():
            form.populate_obj(task)
            db.session.add(task)
            db.session.commit()

            flash(f'Successfully updated task.', 'success')
            return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=form,
                                   project=task.project, task=task, reminder_form=ReminderForm(task_id=task.id))
        else:
            flash(f'Error updating task.', 'error')
            return render_template('task/edit.html', name=current_user.name, title=f"{task.name} | Edit", form=form,
                                   project=task.project, task=task, reminder_form=ReminderForm(task_id=task.id))
    else:
        flash(f'Task does not exist.', 'error')
        return redirect(url_for('projects_controller.index'))


@tasks_controller.route('/tasks/delete', methods=['GET'])
@login_required
def delete_task():
    task_id = request.args.get('task_id')

    task = Task.query.filter(Task.id == task_id)
    project_id = task.first().project.id
    if task:
        task.delete()
    db.session.commit()
    flash(f'Task deleted!', 'success')

    return redirect(url_for('projects_controller.edit_project', project_id=project_id))

templates/project/edit.html
{% extends "base.html" %}
{% set active_page = "projects" %}

{% block content %}


<div class="row">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url_for('projects_controller.index') }}">Projects</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ form.name.data }}</li>
      </ol>
    </nav>
</div>
<div class="row">
    <div class="col">
    <h1>Edit {{ form.name.data }}</h1>
    <div class="card">
        <div class="card-header">
            Edit Project
        </div>
        <div class="card-body">
            <div class="row">

                <div class="col">
                    <form method="POST" action="{{ url_for("projects_controller.edit_project_post", project_id=project_id) }}">
                        {{ form.hidden_tag() }}

                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Project Name:</div>
                                    {{ form.name(class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <div class="input-group">
                                    <div class="input-group-text">Notes:</div>
                                    {{ form.notes(class="form-control") }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary">Edit Project</button>
                            </div>
                        </div>

                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
</div>

<hr>
{% endblock %}

templates/project/index.html
{% extends "base.html" %}
{% set active_page = "projects" %}

{% block content %}

<div class="row">
    <div class="col-6">
        <h1>Create New Project</h1>
        <div class="card">
    <div class="card-header">
        Create New Project
    </div>
    <div class="card-body">

    <div class="row">
    <div class="col">

        <div class="row">
            <form method="POST" action="{{ url_for("projects_controller.new_project_post") }}" class="row row-cols-lg-auto align-items-center">
            {{ form.hidden_tag() }}

            <div class="col-8">
                <div class="input-group">
                  <div class="input-group-text">Project Name:</div>
                    {{ form.name(class="form-control") }}
                </div>
            </div>

            <div class="col-4">
                <button type="submit" class="btn btn-primary">Create Project</button>
            </div>

            </form>
        </div>

    </div>
</div>

    </div>
</div>

    </div>
</div>

<hr>

<h1>Active Projects</h1>
    <div class="row">
        <div class="col">
            {% for project_row in projects | batch(3, '&nbsp;') %}
                <div class="row">
                    {% for project in project_row %}
                        {% if project != '&nbsp;' %}
                        <div class="col-4">
                            <div class="card">
                              <h5 class="card-header">{{ project.name }}</h5>
                              <div class="card-body">
                                <h5 class="card-title">Notes: {{ project.notes[:100] }}</h5>
                                <div class="align-content-center">

                                {% if project.task is not none %}
                                    <p>Next Task: {{ project.task.name }} - {{ project.task.date }}</p>
                                {% endif %}

                                {% if project.reminder is not none %}
                                    <p>Next Reminder: {{ project.reminder.task.name }} -
                                        {{ project.reminder.date_time.strftime('%Y-%m-%d %I:%M %p') }}</p>
                                {% endif %}


                                <a href="{{ url_for('projects_controller.deactivate_project', project_id=project.id) }}"
                                   class="link-danger">Deactivate</a>
                                <a href="{{ url_for('projects_controller.edit_project', project_id=project.id) }}"
                                   class="float-end btn btn-outline-primary">Manage</a>
                                    </div>
                              </div>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endfor %}
        </div>
    </div>
<hr>

<h1>Inactive Projects</h1>
    <div class="row">
        <div class="col">
            {% for project_row in inactive_projects | batch(3, '&nbsp;') %}
                <div class="row">
                    {% for project in project_row %}
                        {% if project != '&nbsp;' %}
                        <div class="col-4">
                            <div class="card">
                              <h5 class="card-header">{{ project.name }}</h5>
                              <div class="card-body">
                                <h5 class="card-title">Notes: {{ project.notes}}</h5>
                                <p class="card-text"></p>

                                <a href="{{ url_for('projects_controller.delete_project', project_id=project.id) }}"
                                   class="link-danger">Delete</a>
                                <a href="{{ url_for('projects_controller.activate_project', project_id=project.id) }}" class="float-end btn btn-outline-primary">Activate</a>

                              </div>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endfor %}
        </div>
    </div>
<hr>
{% endblock %}

templates/project/upcoming.html
{% extends "base.html" %}
{% set active_page = "upcoming" %}

{% block content %}

    <div class="row">
    <div class="col">

    <div class="row">
    <div class="col">
        <div class="row">
            <h3>Upcoming Tasks</h3>
        </div>
        <div class="row">
            <div class="col">
                {% for task_row in tasks[:6] | batch(3, '&nbsp;') %}
                <div class="row">
                    {% for task in task_row %}
                        {% if task != '&nbsp;' %}
                        <div class="col-4">
                            <div class="card">
                              <h5 class="card-header">
                                  {{ task.name }} - {{ task.date }}
                                  {% if task.start_time is not none %}

                                    (
                                    {{ task.start_time.strftime("%I:%M %p") }} ->
                                    {{ task.end_time.strftime("%I:%M %p") }}
                                    )

                                    {% endif %}
                                  <button type="button" class="float-end btn btn-primary">
                                    Reminders <span class="badge rounded-pill bg-info">{{ task.reminder_count }}</span>
                                </button>
                              </h5>
                              <div class="card-body">
                                <p class="card-text">
                                    <div class="row">
                                        <div class="col">
                                            <div class="row">
                                                {{ task.notes }}
                                            </div>
                                            <div class="row">
                                                <a href="{{ url_for('tasks_controller.edit_task', task_id=task.id) }}" class="btn btn-secondary">Edit</a>
                                            </div>
                                        </div>
                                    </div>
                                  </p>
                              </div>
                            </div>
                            <div class="card-footer">
                                <a href="{{ url_for('tasks_controller.delete_task', task_id=task.id) }}" class="link-danger">Delete</a>
                                <a class="float-end btn btn-outline-primary">Completed</a>
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<hr>
    </div>
    </div>
{% endblock %}